// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteConquest.Infra.Data.Context;

namespace TesteConquest.Infra.Data.Migrations
{
    [DbContext(typeof(ConquestContext))]
    [Migration("20190809023659_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TesteConquest.Domain.Entities.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("NomeExibicao")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Autor");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomeCompleto = "Paulo Coelho",
                            NomeExibicao = "COELHO, Paulo"
                        },
                        new
                        {
                            Id = 2,
                            NomeCompleto = "Monteiro Lobato",
                            NomeExibicao = "LOBATO, Monteiro"
                        },
                        new
                        {
                            Id = 3,
                            NomeCompleto = "José de Alencar",
                            NomeExibicao = "ALENCAR, José de"
                        },
                        new
                        {
                            Id = 4,
                            NomeCompleto = "João Cabral de Melo Neto",
                            NomeExibicao = "MELO NETO, João Cabral de"
                        },
                        new
                        {
                            Id = 5,
                            NomeCompleto = "Cecília Meireles",
                            NomeExibicao = "MEIRELES, Cecília"
                        },
                        new
                        {
                            Id = 6,
                            NomeCompleto = "Guimarães",
                            NomeExibicao = "GUIMARÃES"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
